### ISSUE TITLE
Informal meeting about studyGroup at UiO

### ISSUE THREAD

**Issue by annefou** [uio-carpentry/studyGroup#1]
Informal meeting with anyone showing interest with UiO-Carpentry StudyGroup.

**Where**: Science Library - Vilhelm Bjerknes' hus
See http://www.uio.no/om/finn-fram/omrader/blindern/bl13/ to reach us
**When**: Thursday, July 12, 9:00-11:00
**What to prepare**: Come with ideas on what and how you would like to run the UiO studyGroup
**What to bring**: A laptop
**Preliminary program**:

9:00-09:30: What is UiO-Carpentry StudyGroup and what do we expect?
09:30-10:00: short presentations (5 mn) on possible contributions
10:00-10:45: discussions and list of actions
10:45-11:00: wrap-up

**Comment by annefou** [comment]
# Meeting Minutes #

## Attendees ##
**Present**: Gladys Nalvarte, Ana Costa Conrado, Anne Fouilloux

## Adoption of Agenda ##

The agenda was adopted. We agreed on the fact that this meeting is fairly informal and a more formal meeting will be organized after mid-august.

### What is UiO-Carpentry StudyGroup and what do we expect? ###

The UiO-Carpentry StudyGroup will complement Uio@Carpentry workshops by offering:

- Book club discussion: we will gather a list of books that could be of interest and could be discussed. Subjects range from personal development, pedagogy to technical subjects (emerging programming languages, etc.)
- Train the Trainer: short lesson on a subject with an aim to enhance technical skills of our set of Carpentry Instructors
- Study Group Lessons: develop (or re-use existing material available for Study Group  Lessons) and teach short lesson on a technical subject that is of interest but cannot be taught as an entire workshop or for which no Carpentries lesson is available.

### short presentations (5 mn) on possible contributions ###

- Gladys can contribute on advanced lessons for instance on pytest. She will also participate in the book club discussions.
- Ana can contribute on study Group lessons on machine & deep learning
- Anne can set-up and update the StudyGroup website and help to organize the book club, etc.

### list of actions ###

- [x] **Anne**: update studyGroup website with:
    * lesson tab: to gather lesson materials and link to Software and Data Carpentry  lessons
    * Add a tab to nordic-RSE initiative
    * Add a tab to Book club
- [ ] **Gladys & Anne**: Develop a short lesson on the advanced usage of pytest.
- [ ] **Ana**: Develop a short introduction on machine & deep learning

**Comment by arockenberger** [comment]
Thanks, Anne, for organising this!
I would like to be part of the StudyGroup, too. I'm no longer at UiO, though. I hope, this isn't a problem!

**Comment by annefou** [comment]
Great! I added you in the list of members. Welcome!!!

**Comment by arockenberger** [comment]
Move either to now folder or Wiki - close issue afterwards
