### ISSUE TITLE
Add events to the Google Calendar

### ISSUE THREAD

**Issue by lexnederbragt** [uio-carpentry/studyGroup#16]
We have a Carpentry@UiO calendar that maybe could ave all the study groups events listed as well? @dmi3kno is in charge of the calendar, I think.

**Comment by dmi3kno** [comment]
I certainly have access. I have scheduled the events I could find in the [workshop plan](https://docs.google.com/spreadsheets/d/1JJ5Fb5F17PiLk1TrgDUIyuLIQVvXNsVYBG3ggZArEzU/edit#gid=113397920). Let me know if you want to change/add something

**Comment by lexnederbragt** [comment]
Thanks for that! But this issue refers to events _in addition_ to the workshops. Those 'Study Group' events you can find [here](https://uio-carpentry.github.io/studyGroup/#portfolio).

**Comment by annefou** [comment]
?I am adding it in the list of events.


Anne.

________________________________

**Comment by annefou** [comment]
I close this issue as I think it is solved.

**Comment by lexnederbragt** [comment]
Hmm I am afraid not. I see the regular workshops in my calendar, but not the study group sessions...

**Comment by annefou** [comment]
So I am lost... Which calendar are you talking about?

**Comment by lexnederbragt** [comment]
google calendar, Carpentry@UiO.
