### ISSUE TITLE
Oslo useR! Group: Functions, loops and list-columns: taking control of lists with purrr

### ISSUE THREAD

**Issue by annefou** [uio-carpentry/studyGroup#17]
**Details**

Are you still writing `for` loops? What are some of the advantages of functional programming in R? What makes a good function? How to take control of nested lists and turn chaos into order? Come and explore a fun world of {purrr} and discover hidden gems in this awesome tidyverse package. Filled with practical examples from author's recently published packages, this talk may help you discover some of the new (and old) functions you may not have used before and encourage you on your journey to becoming a better R programmer.

_Bring your laptop if you want to try it out!_

**Level**: beginner to intermediate
**When**: 19th September 2018, 17:30-19:30
**Location**:   Microsoft Norge, Lysaker Torg 45 · Lysaker
**More information**: https://www.meetup.com/Oslo-useR-Group/events/254422876/

**Comment by anacost** [comment]
I do not understand why on the page it is displayed 6th September... The post is correct. Where does it come from?? I wanted to correct it myself to 19th September so I could help you.
