### ISSUE TITLE
'Add to calendar' button/link

### ISSUE THREAD

**Issue by lexnederbragt** [uio-carpentry/studyGroup#19]
Would it be possible to have a 'Add to calendar' button/link for each Study Group event at https://uio-carpentry.github.io/studyGroup/?

**Comment by annefou** [comment]
Yes. But which calendars should we over? Google calendar, etc?

**Comment by lexnederbragt** [comment]
As far as I know, it requires a single `.ics` file and then the user picks their calendar program.

**Comment by arockenberger** [comment]
We don't want to do this now. Perhaps in the future we can reconsider it. Closing the issue. :)
