### ISSUE TITLE
Notes from StudyGroup sessions - where?

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/studyGroup#20]
Hei!

I took notes for the session on Sep 7. Where should I put it? It doesn't look well putting it in the post for the event, so perhaps somewhere under lessons? Ideas??

Cheers,

Annika

**Comment by annefou** [comment]
Normally we use git submodule. Do you only have notes? Did you have some other materials such as slides, etc.

**Comment by arockenberger** [comment]
Only notes, no slides; we did live view of websites to which I have the links.
What is git submodule??

**Comment by heereman** [comment]
Have you managed to put the notes somewhere?

**Comment by annefou** [comment]
No we did not. I was too busy last week. I'll have a look next Monday.

**Comment by annefou** [comment]
I think the easiest is to add notes in our lesson sections. I created a new directory NDA-minutes with a README.md file where you can add your notes in it. When we will have more extensive lessons/tutorials, we can use git sub-modules. I don't think it is worth in this case.

**Comment by arockenberger** [comment]
Hei!
I added the notes for the NDA session – and close the issue hereby!
