### ISSUE TITLE
Mailing list or not??

### ISSUE THREAD

**Issue by anacost** [uio-carpentry/studyGroup#24]
Hi, 
should we have a mailing-list to announce our events to interested people?

The events could be listed in the calendar of the library or we could advertise for our mailing-list on the page of the library.

**Comment by arockenberger** [comment]
In any case, we need better advertising.

I’m not sure another mailing list does the trick though. But having the events on the library’s website would be good. I’ve been distributing study group sessions via the digital humanities list, but they are notoriously hard to attract as long as it’s not explicitly digital humanities related content.

Perhaps a poster in realfagsbiioteket?
And advertise harder on the SWC mailing lists?!

Cheers,

Annika

**Comment by annefou** [comment]
I am preparing an email to be send to Carpentry@UiO.

**Comment by anacost** [comment]
I have asked the realfagsbiblioteket. They do not like posters, no paper on the walls. 
We should start advertising on the SWC mailing list and be able to publish on the page of the library with all the other SWC courses.

**Comment by annefou** [comment]
Hi everyone,

Have you had a chance to check out the Carpentry@UiO Study Group that's started here at the University of Oslo? We're a group of scientists, researchers and students who get together to share skills and work together on problems like programming for research, open science strategies, and data management in the lab. Check out our event listings on our website: https://uio-carpentry.github.io/studyGroup/#portfolio

Most Study Group sessions are about two hours long tutorials, where one person from our community leads a hands-on demonstration of an idea, package, or piece of code, while everyone else follows along; also, we'll get together once in a while for open co-working sessions to work on our own research projects and get help with questions as they arise. The tutorial sessions are lead by volunteers, most of them involved in Carpentry@UiO workshops and the curriculum and schedule is up to us to set.

Everyone is welcome - Study Groups work best when they reflect what the community wants, so come out and let us know! If you can't make it but have ideas or questions, please post a thread on our issue tracker (https://github.com/uio-carpentry/studyGroup/issues/new).

**Comment by anacost** [comment]
I like the email. Thank you!!

**Comment by arockenberger** [comment]
I can send that email via the digitalhumaniora@hf.uio.no mailing list, too!
