### ISSUE TITLE
Our events on Meetup?!

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/studyGroup#28]
Hei!
What do you think about creating a meetup group and add our events there, too? It might be easier to get an overview over who’s coming and other people can join easier, too.

Yes/No/Maybe?

**Comment by annefou** [comment]
Yes. It's a very good idea.

**Comment by anacost** [comment]
yes, it will be visible outside

**Comment by arockenberger** [comment]
I just found out that in order to create a group on Meetup, one has to pay a fee. Do we have someone in our midst that already pays this fee and can create a group for us with the events?

**Comment by lexnederbragt** [comment]
You could try Athanasia or Dmytro. Or: how much is the fee? Maybe the library can sponsor it...

**Comment by arockenberger** [comment]
The cheapest is 5$ per month (50 members, 4 organisers). The "unlimited" is 8$ per month.
