### ISSUE TITLE
Zotero Reference Manager and Research Assistant

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/studyGroup#31]
I want to develop a one-day workshop teaching the Zotero reference management system to novices. During this session, I will walk you through the main features of Zotero in both the browser and the standalone version and show you some of the more advanced features that Zotero provides, too.

When: 25th January 2019
Time: 14:00-16:00
Location: Vilhelm Bjerknes’ hus, room 123

**Comment by arockenberger** [comment]
Good starting point (https://www.zotero.org/support/present)

**Comment by lexnederbragt** [comment]
See also https://www.ub.uio.no/english/courses-events/events/all-libraries/2018/180208co-writing.html. Solveig apparently is leaving UiO, Heidi still works at the library.

**Comment by arockenberger** [comment]
I would really like to host a study group session on this topic, but unfortunately, the session on Jan 25 had to be cancelled. If it were held at Nat.Lib., would this be ok for the Blindern-based folk?
