### ISSUE TITLE
Voila python package

### ISSUE THREAD

**Issue by annefou** [uio-carpentry/studyGroup#48]
Voilà turns Jupyter notebooks into standalone web applications.

See 

- https://blog.jupyter.org/and-voil%C3%A0-f6a2c08a4a93
- https://voila.readthedocs.io/en/latest/
- https://voila-gallery.org/services/gallery/

**Comment by arockenberger** [comment]
Responsible: Anne F.
Date: Sep 26

Let's explore Voilà together and see if it holds up!
