### ISSUE TITLE
Carpentries Hacktoberfest: Tag-a-thon in week 44

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/studyGroup#64]
Dear all,

The Carpentries has set up a week-long remote event in Hackathon-style.
https://carpentries.org/blog/2019/10/carpentries-tagathon/

Everyone is invited to read blog posts on Software, Data, and Library Carpentry websites and tag them.

As you know, I dislike reading – so I thought we could make a computer do the reading instead and come up with a couple of topics that could be used for tagging the blog posts. I have run a small test using Pandoc and VoyantTools – and I invite you all to come join me in a StudyGroup on Oct 17 for the Tagathon using machine skills instead of human skills to get the task done ;)!

**Comment by arockenberger** [comment]
https://github.com/uio-carpentry/studyGroup/blob/gh-pages/_posts/2019-10-17-tagathon.markdown - preparation StudyGroup for Hacktoberfest

**Comment by eapapp** [comment]
Sounds fun! Count me in.

**Comment by arockenberger** [comment]
I made a mistake with the date for the Studygroup: it’s Oct 17!

**Comment by arockenberger** [comment]
@Teebusch created a repository for our Hackathon contribution [on the Carpentry@UiO GitHub](https://github.com/uio-carpentry/carpentries-tagathon). Let's continue working on this! I will add a less chaotic description of what my initial idea was to the README.md and sketch a workflow.
