### ISSUE TITLE
Planning Meeting Jan 23, 2020

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/studyGroup#66]
We meet and plan the spring term 2020!

There will be coffee, tea, and maybe cookies!

**Comment by naoe-tatara** [comment]
Have booked room 209 on the Jan 16th, 16:00-18:00. Shall we announce the change of the date and eventually cancel the one on Jan 23rd?

**Comment by arockenberger** [comment]
We met, but neither coffee nor cookies were there (think of the Swedes!)
