### ISSUE TITLE
coworking/ oslo study group more accessible? 

### ISSUE THREAD

**Issue by evezeyl** [uio-carpentry/studyGroup#68]
That would be great if we could extend the possibilities of participations of the studygroup through remote participation. 

- would increase posibilities of participations (ie: living far away, working abroad during this period, cannot make it at the time of study group because meetings at another place just before, osv....)  
- could allow people not in Oslo to contribute to our workshop, then might help increase number of participants

Would require (at least):
- choosing tools for video-conferencing
- choosing tools for sharing notes, co-coding... ie? classroom type?

**Comment by arockenberger** [comment]
Hei all, thanks for the StudyGroup session on this topic!
We will try out Skype (for business) since it is approved by UiO and we can run it on the stationary pc in the room we are using.
It should be possible to connect to the video call using Skype (private), also via phone, tablet etc.
If you cannot come to a StudyGroup you are interested in, please let us know and we will open a remote connection for you via Skype!

**Comment by lexnederbragt** [comment]
Good idea! Just so you know: Zoom, used by The Carpentries, is now also available for UiO, via https://uio.zoom.us. I guess there are advantages for each system and perhaps we could try out both?

**Comment by arockenberger** [comment]
That just made me so happy! Yuhuu!!!

**Comment by arockenberger** [comment]
As of March 19, we are using Zoom for the StudyGroup during the Covid-19 physical distancing measures. We can afterward continue to use Zoom for those StudyGroup members that cannot be on site.
-------------------------------------
Annika Rockenberger is inviting you to a scheduled Zoom meeting.

Topic: StudyGroup
Time: Mar 19, 2020 04:00 PM Oslo
Every week on Thu, until Apr 16, 2020, 5 occurrence(s)
Mar 19, 2020 04:00 PM
Mar 26, 2020 04:00 PM
Apr 2, 2020 04:00 PM
Apr 9, 2020 04:00 PM
Apr 16, 2020 04:00 PM
Please download and import the following iCalendar (.ics) files to your calendar system.
Weekly: https://uio.zoom.us/meeting/tZMkc-murjMs_R5AT21gTPj-g2C3rtmK0A/ics?icsToken=98tyKuGvpz8qHNSdtl3tf60qW4H4bPHMkU58_4Jpzk7iNxBZLwSkFbFQJr9UQPmB

Join Zoom Meeting
https://uio.zoom.us/j/879406086

Meeting ID: 879 406 086

One tap mobile
+4723960588,,879406086# Norway
+4773494877,,879406086# Norway

Dial by your location
+47 2396 0588 Norway
+47 7349 4877 Norway
Meeting ID: 879 406 086
Find your local number: https://uio.zoom.us/u/ccDmUrivsL

Join by SIP
879406086@109.105.112.236
879406086@109.105.112.235

Join by H.323
109.105.112.236
109.105.112.235
Meeting ID: 879 406 086

Join by Skype for Business
https://uio.zoom.us/skype/879406086

**Comment by arockenberger** [comment]
See above, I'm closing the issue. I will add the Zoom link to the StudyGroup calendar.
